import type { ColumnDefinition, SchemaExport } from '@openbase/core'

const jsonType = `export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]`

export function generateTypescriptSchemaClient(schemaExport: SchemaExport): string {
    const tables = Object.entries(schemaExport.tables)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([tableName, schema]) => renderTableType(tableName, schema.columns))
        .join('\n\n')

    const tableNames = Object.keys(schemaExport.tables)
        .sort()
        .map(name => `'${name}'`)
        .join(' | ') || 'never'

    return [
        `/* eslint-disable */`,
        `// Generated by openbase gen types for project ${schemaExport.projectName} (${schemaExport.projectId})`,
        `import { createClient, type OpenBaseClient, type QueryBuilder } from 'openbase-js'`,
        '',
        jsonType,
        '',
        'export interface Database {',
        '  public: {',
        '    Tables: {',
        tables.split('\n').map(line => `      ${line}`).join('\n'),
        '    }',
        '  }',
        '}',
        '',
        `export type TableName = ${tableNames}`,
        'export type TableRow<T extends TableName> = Database[\'public\'][\'Tables\'][T][\'Row\']',
        'export type TableInsert<T extends TableName> = Database[\'public\'][\'Tables\'][T][\'Insert\']',
        'export type TableUpdate<T extends TableName> = Database[\'public\'][\'Tables\'][T][\'Update\']',
        '',
        'export type OpenBaseTypedClient = Omit<OpenBaseClient, \'from\'> & {',
        '  from<T extends TableName>(table: T): QueryBuilder<TableRow<T>, TableInsert<T>, TableUpdate<T>>',
        '}',
        '',
        'export function createTypedClient(projectUrl: string, anonKey: string): OpenBaseTypedClient {',
        '  return createClient(projectUrl, anonKey) as OpenBaseTypedClient',
        '}',
        '',
    ].join('\n')
}

function renderTableType(tableName: string, columns: ColumnDefinition[]): string {
    const rowFields = columns
        .map(column => `        ${formatKey(column.name)}: ${renderType(column, !column.required)}`)
        .join('\n')

    const insertFields = columns
        .map(column => `        ${formatKey(column.name)}${column.required ? '' : '?'}: ${renderType(column, true)}`)
        .join('\n')

    const updateFields = columns
        .map(column => `        ${formatKey(column.name)}?: ${renderType(column, true)}`)
        .join('\n')

    return [
        `${formatKey(tableName)}: {`,
        '      Row: {',
        rowFields,
        '      }',
        '      Insert: {',
        insertFields,
        '      }',
        '      Update: {',
        updateFields,
        '      }',
        '    }',
    ].join('\n')
}

function renderType(column: ColumnDefinition, optional: boolean): string {
    const baseType = (() => {
        switch (column.type) {
            case 'text':
            case 'uuid':
            case 'timestamp':
                return 'string'
            case 'number':
                return 'number'
            case 'boolean':
                return 'boolean'
            case 'json':
                return 'Json'
        }
    })()

    return optional ? `${baseType} | null` : baseType
}

function formatKey(value: string): string {
    return /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(value) ? value : JSON.stringify(value)
}
